#config-dev.yml
config:
  info: "master branch,springcloud-config/config-dev.yml version=1"
  
#######################################

#config-prod.yml
config:
  info: "master branch,springcloud-config/config-prod.yml version=1"

#######################################

#config-test.yml
config:
  info: "master branch,springcloud-config/config-test.yml version=1"

